---
name: Build Tagged Image

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"

jobs:
  build-containers-on-tag:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Get tag from actions context
        id: gitref_tag
        run: echo ::set-output name=tag::${GITHUB_REF##*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build stage 1
        uses: docker/build-push-action@v3
        with:
          context: docker-stage1
          file: docker-stage1/Dockerfile
          cache-from: type=gha,scope=ug-chromium-stage1
          cache-to: type=gha,scope=ug-chromium-stage1,mode=max
          load: true
          tags: |
            ug-chromium-builder-stage1:${{ steps.gitref_tag.outputs.tag }}
            ug-chromium-builder-stage1:latest

      - name: Browser build stage
        run: |
          docker run -v `pwd`:/repo:z ug-chromium-builder-stage1:${{ steps.gitref_tag.outputs.tag }} bash -c "./build.sh && ./package.sh"

      - name: Build Appimage stage
        run: |
          docker run -v `pwd`:/repo:z ug-chromium-builder-stage1:${{ steps.gitref_tag.outputs.tag }} bash -c "./package.appimage.sh.ungoogin"

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/ungoogled-chromium*"
          artifactContentType: application/gzip
          omitBodyDuringUpdate: false
          omitName: true
          omitNameDuringUpdate: true
          tag: ${{ steps.gitref_tag.outputs.tag }}
